apiVersion: koku-metrics-cfg.openshift.io/v1beta1
kind: KokuMetricsConfig
metadata:
  name: kokumetricscfg
  namespace: koku-metrics-operator
spec:
  authentication: {}
  packaging:
    max_reports_to_store: 25
    max_size_MB: 100
  prometheus_config: {}
  source: {}
  upload:
    upload_cycle: 360
    upload_toggle: false